name: ccid_task_2
run-name: ${{ github.actor }} triggered with ${{ github.sha }}

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  PYTHON_VERSION : 3.8

jobs:
  python-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/
    steps:
      - uses: actions/checkout@v4
      # runs the tests

      # generates a coverage

      # displays the coverage report

      # checks the code style

      # checks the complexity of the code

      # Python code as an artifact
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '${{ env.PYTHON_VERSION }}'

      - name: Run app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py runserver


      # - name: Show GITHUB_ACTIONS enviroment variables
      #   run: |
      #     echo "GITHUB_ACTIONS=$GITHUB_ACTIONS"

      # - name: Show branch and repository name
      #   run: |
      #     echo "Repository: ${{ github.repository }}. Branch: ${{ github.ref }}"

      # - name: Show action that triggered workflow
      #   run: |
      #     echo "Job was triggered by ${{ github.event_name }}"